### ISSUE TITLE
MouseWheel event doesn't work in Opera 12.15

### ISSUE THREAD

**Issue by DartBot** [dart-lang/sdk#11714]
_This issue was originally filed by @dangreen_

---

Opera can't get deltaX and deltaY props

&nbsp;&nbsp;&nbsp;&nbsp;t2 = t1.get$deltaX(e); 
&nbsp;&nbsp;&nbsp;&nbsp;Unhandled Error: 't1.get$deltaX' is not a function

But Opera's event object looks like a WebKit mousewheel event object.
