### ISSUE TITLE
Flutter doctor failed

### ISSUE THREAD

**Issue by ryanfang** [dart-lang/sdk#32037]
Analyzer Feedback from IntelliJ

# Version information

- `IDEA IU-173.4548.28`
- `2.0.0-dev.16.0`
- `IU-173.4548.28, JRE 1.8.0_152-release-1024-b11x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.3 unknown, screens 1280x800  Retina`

# Exception

Please append the contents of:
file:///private/var/folders/pc/znf5nspx5h7_l3f9qksn4tp40000gn/T/report.txt

```
Dart analysis server, SDK version 2.0.0-dev.16.0, server version 1.18.4, error: Analysis failed: /Users/fangtao/Documents/FlutterWorkspace/Projects/SafeMonitor/gs_safe_monitor/test/widget_test.dart context: exception_20180205_005456_005
NoSuchMethodError: Class 'DynamicElementImpl' has no instance getter 'supertype'.
Receiver: Instance of 'DynamicElementImpl'
Tried calling: supertype
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:478)
#2      InheritanceManager._computeInterfaceLookupMap (package:analyzer/src/dart/resolver/inheritance_manager.dart:450)
#3      InheritanceManager._gatherInterfaceLookupMaps (package:analyzer/src/dart/resolver/inheritance_manager.dart:496)
#4      InheritanceManager.lookupOverrides (package:analyzer/src/dart/resolver/inheritance_manager.dart:205)
#5      InstanceMemberInferrer._computeFieldOverrideType (package:analyzer/src/task/strong_mode.dart:114)
#6      InstanceMemberInferrer._inferField (package:analyzer/src/task/strong_mode.dart:403)
#7      InstanceMemberInferrer._inferClass.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:308)
#8      List.forEach (dart:core-patch/dart:core/growable_array.dart:274)
#9      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:307)

**Comment by devoncarew** [comment]
It looks like you're running on `2.0.0-dev.16.0`; were you by chance trying the --preview-dart-2 flag? If so, that's know not to work with `2.0.0-dev.16.0` - you'll want to move to dev23.

**Comment by zoechi** [comment]
This seems to be quite common recently. 
`flutter upgrade` doesn't seem to actually upgrade and also doesn't cause an error.
People then think they got the latest version but they didn't.
I suggested (on Gitter) several times to just purge the `flutter` directory and clone it again.
This usually fixed the issues.

**Comment by devoncarew** [comment]
/cc @jcollins-g for possible issues with `flutter upgrade`

@zoechi, thanks! Purging the directory seems like a reasonable workaround.

**Comment by kevmoo** [comment]
Seems a dupe of https://github.com/dart-lang/sdk/issues/30865
