### ISSUE TITLE
Failures on [vm] Correct comment...[vm] Move kHashBits to Object

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#46820]
There are new test failures on [[vm] Correct comment...[vm] Move kHashBits to Object](https://github.com/dart-lang/sdk/compare/e79e0020ceb6808745f2bbdd0789fe2ba621d9d2~...56bd70b257366b2f1422166676326fb6bc93b793).

The tests
```
standalone_2/io/file_system_watcher_large_set_test/0 Crash (expected Pass)
standalone_2/io/file_system_watcher_large_set_test/1 Crash (expected Pass)
standalone_2/io/socket_connect_stacktrace_test Crash (expected Pass)
standalone_2/io/socket_sigpipe_test Crash (expected Pass)
```
are failing on configurations
```
dartk-reload-linux-debug-x64
```

Log:
```
--- Command "vm" (took 09.000258s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --hot-reload-test-mode --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/standalone_2/io/socket_sigpipe_test.dart

exit code:
-6

stdout:
unittest-suite-wait-for-done

stderr:
../../runtime/vm/isolate_reload.cc: 2277: error: expected: !FLAG_identity_reload
version=2.14.0-edge.56bd70b257366b2f1422166676326fb6bc93b793 (be) (Thu Aug 5 00:37:47 2021 +0000) on "linux_x64"
pid=10523, thread=10566, isolate_group=main(0x555f773e0800), isolate=(nil)((nil))
isolate_instructions=555f74b47860, vm_instructions=555f74b47860
  pc 0x0000555f74f3cddc fp 0x00007f9d3667d130 dart::Profiler::DumpStackTrace(void*)+0x7c
  pc 0x0000555f74b47a14 fp 0x00007f9d3667d210 dart::Assert::Fail(char const*, ...)+0x84
  pc 0x0000555f74de920c fp 0x00007f9d3667d2e0 out/DebugX64/dart+0x20e920c
  pc 0x0000555f74de8370 fp 0x00007f9d3667d3f0 dart::ProgramReloadContext::InvalidateFields(dart::Zone*, dart::GrowableArray<dart::Field const*> const&, dart::GrowableArray<dart::Instance const*> const&)+0xc0
  pc 0x0000555f74de79ef fp 0x00007f9d3667d540 dart::ProgramReloadContext::RunInvalidationVisitors()+0x2ff
  pc 0x0000555f74de69a8 fp 0x00007f9d3667d5a0 dart::ProgramReloadContext::InvalidateWorld()+0xb8
  pc 0x0000555f74de0dff fp 0x00007f9d3667d600 dart::ProgramReloadContext::ReloadPhase4CommitFinish()+0x6f
  pc 0x0000555f74ddddbe fp 0x00007f9d3667d8b0 dart::IsolateGroupReloadContext::Reload(bool, char const*, char const*, unsigned char const*, long)+0x11be
  pc 0x0000555f74dd3940 fp 0x00007f9d3667d930 dart::IsolateGroup::ReloadSources(dart::JSONStream*, bool, char const*, char const*, bool)+0x1c0
  pc 0x0000555f74facf8c fp 0x00007f9d3667db00 dart::DRT_StackOverflow(dart::NativeArguments)+0x39c
  pc 0x00007f9d42502812 fp 0x00007f9d3667db40 Unknown symbol
  pc 0x00007f9d3c68b09a fp 0x00007f9d3667db88 Unknown symbol
  pc 0x00007f9d3c689664 fp 0x00007f9d3667dc10 Unknown symbol
  pc 0x00007f9d3c6889ed fp 0x00007f9d3667dc68 Unknown symbol
  pc 0x00007f9d3c6855ae fp 0x00007f9d3667dd38 Unknown symbol
  pc 0x00007f9d3c680eca fp 0x00007f9d3667dd88 Unknown symbol
  pc 0x00007f9d3c680981 fp 0x00007f9d3667ddf0 Unknown symbol
  pc 0x00007f9d3c6a8c79 fp 0x00007f9d3667de30 Unknown symbol
  pc 0x00007f9d3c6a8abe fp 0x00007f9d3667de58 Unknown symbol
  pc 0x00007f9d3c6a895b fp 0x00007f9d3667de90 Unknown symbol
  pc 0x00007f9d3c6af1b2 fp 0x00007f9d3667deb8 Unknown symbol
  pc 0x00007f9d3c6af109 fp 0x00007f9d3667dee0 Unknown symbol
  pc 0x00007f9d42502c9d fp 0x00007f9d3667df48 Unknown symbol
  pc 0x0000555f74d966b4 fp 0x00007f9d3667dfe0 dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*)+0x134
  pc 0x0000555f74d9627e fp 0x00007f9d3667e050 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x16e
  pc 0x0000555f74e8c19b fp 0x00007f9d3667e0a0 dart::Field::InitializeStatic() const+0x17b
  pc 0x0000555f74fb1952 fp 0x00007f9d3667e180 dart::DRT_InitStaticField(dart::NativeArguments)+0x1a2
  pc 0x00007f9d42502812 fp 0x00007f9d3667e1c8 Unknown symbol
  pc 0x00007f9d42505e09 fp 0x00007f9d3667e1f8 Unknown symbol
  pc 0x00007f9d3c6af082 fp 0x00007f9d3667e220 Unknown symbol
  pc 0x00007f9d3c6aef65 fp 0x00007f9d3667e250 Unknown symbol
  pc 0x00007f9d3c6aeeaf fp 0x00007f9d3667e288 Unknown symbol
  pc 0x00007f9d3c6aedd9 fp 0x00007f9d3667e2b0 Unknown symbol
  pc 0x00007f9d42502c9d fp 0x00007f9d3667e318 Unknown symbol
  pc 0x0000555f74d966b4 fp 0x00007f9d3667e3b0 dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*)+0x134
  pc 0x0000555f74d9627e fp 0x00007f9d3667e420 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x16e
  pc 0x0000555f74e8c19b fp 0x00007f9d3667e470 dart::Field::InitializeStatic() const+0x17b
  pc 0x0000555f74fb1952 fp 0x00007f9d3667e550 dart::DRT_InitStaticField(dart::NativeArguments)+0x1a2
  pc 0x00007f9d42502812 fp 0x00007f9d3667e590 Unknown symbol
  pc 0x00007f9d42505e09 fp 0x00007f9d3667e5c0 Unknown symbol
  pc 0x00007f9d3c6aed52 fp 0x00007f9d3667e5e8 Unknown symbol
  pc 0x00007f9d3c6aec82 fp 0x00007f9d3667e610 Unknown symbol
  pc 0x00007f9d3c6a6cc5 fp 0x00007f9d3667e6a8 Unknown symbol
  pc 0x00007f9d3c6a5f96 fp 0x00007f9d3667e6d8 Unknown symbol
  pc 0x00007f9d3c6a5bfe fp 0x00007f9d3667e700 Unknown symbol
  pc 0x00007f9d3c6a5b12 fp 0x00007f9d3667e760 Unknown symbol
  pc 0x00007f9d3c6a48e5 fp 0x00007f9d3667e798 Unknown symbol
  pc 0x00007f9d3c6a4655 fp 0x00007f9d3667e800 Unknown symbol
  pc 0x00007f9d3c6a3ec0 fp 0x00007f9d3667e840 Unknown symbol
  pc 0x00007f9d42502c9d fp 0x00007f9d3667e8b8 Unknown symbol
  pc 0x0000555f74d966b4 fp 0x00007f9d3667e950 dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*)+0x134
  pc 0x0000555f74d9627e fp 0x00007f9d3667e9c0 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x16e
  pc 0x0000555f74d99467 fp 0x00007f9d3667ea20 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)+0x117
  pc 0x0000555f74dd0381 fp 0x00007f9d3667eb20 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x5a1
  pc 0x0000555f74e138b8 fp 0x00007f9d3667ebb0 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x218
  pc 0x0000555f74e14694 fp 0x00007f9d3667ec30 dart::MessageHandler::TaskCallback()+0x344
  pc 0x0000555f74ff45fb fp 0x00007f9d3667ecd0 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x1fb
  pc 0x0000555f74ff4f97 fp 0x00007f9d3667ed20 dart::ThreadPool::Worker::Main(unsigned long)+0x147
  pc 0x0000555f74f34514 fp 0x00007f9d3667ee70 out/DebugX64/dart+0x2234514
-- End of DumpStackTrace
[exit     : sp(0) fp(0x7f9d3667db40) pc(0)]
[dart     : sp(0x7f9d3667db50) fp(0x7f9d3667db88) pc(0x7f9d3c68b09a) dart:core_StringBuffer_StringBuffer. ]
[dart     : sp(0x7f9d3667db98) fp(0x7f9d3667dc10) pc(0x7f9d3c689664) dart:_internal_ListIterable_join ]
[dart     : sp(0x7f9d3667dc20) fp(0x7f9d3667dc68) pc(0x7f9d3c6889ed) dart:core__Uri@0150898__makePath@0150898 ]
[dart     : sp(0x7f9d3667dc78) fp(0x7f9d3667dd38) pc(0x7f9d3c6855ae) dart:core__Uri@0150898__Uri@0150898. ]
[dart     : sp(0x7f9d3667dd48) fp(0x7f9d3667dd88) pc(0x7f9d3c680eca) dart:core__Uri@0150898__makeFileUri@0150898 ]
[dart     : sp(0x7f9d3667dd98) fp(0x7f9d3667ddf0) pc(0x7f9d3c680981) dart:core__Uri@0150898__Uri@0150898.directory ]
[dart     : sp(0x7f9d3667de00) fp(0x7f9d3667de30) pc(0x7f9d3c6a8c79) dart:io_::__uriBaseClosure@14069316 ]
[dart     : sp(0x7f9d3667de40) fp(0x7f9d3667de58) pc(0x7f9d3c6a8abe) dart:io_::__uriBaseClosure@14069316__uriBaseClosure@14069316 ]
[dart     : sp(0x7f9d3667de68) fp(0x7f9d3667de90) pc(0x7f9d3c6a895b) dart:core_Uri_get_base ]
[dart     : sp(0x7f9d3667dea0) fp(0x7f9d3667deb8) pc(0x7f9d3c6af1b2) package:path/src/style.dart_Style__getPlatformStyle@25105565 ]
[dart     : sp(0x7f9d3667dec8) fp(0x7f9d3667dee0) pc(0x7f9d3c6af109) package:path/src/style.dart_Style_init_platform ]
[entry    : sp(0x7f9d3667def0) fp(0x7f9d3667df48) pc(0x7f9d42502c9d)]
[exit     : sp(0) fp(0x7f9d3667e1c8) pc(0)]
[stub     : sp(0x7f9d3667e1d8) fp(0x7f9d3667e1f8) pc(0x7f9d42505e09)]
[dart     : sp(0x7f9d3667e208) fp(0x7f9d3667e220) pc(0x7f9d3c6af082) package:path/src/style.dart_Style_get_platform ]
[dart     : sp(0x7f9d3667e230) fp(0x7f9d3667e250) pc(0x7f9d3c6aef65) package:path/src/context.dart_Context_Context._internal@24448123 ]
[dart     : sp(0x7f9d3667e260) fp(0x7f9d3667e288) pc(0x7f9d3c6aeeaf) package:path/src/context.dart_::_createInternal ]
[dart     : sp(0x7f9d3667e298) fp(0x7f9d3667e2b0) pc(0x7f9d3c6aedd9) package:path/path.dart_::_init_context ]
[entry    : sp(0x7f9d3667e2c0) fp(0x7f9d3667e318) pc(0x7f9d42502c9d)]
[exit     : sp(0) fp(0x7f9d3667e590) pc(0)]
[stub     : sp(0x7f9d3667e5a0) fp(0x7f9d3667e5c0) pc(0x7f9d42505e09)]
[dart     : sp(0x7f9d3667e5d0) fp(0x7f9d3667e5e8) pc(0x7f9d3c6aed52) package:path/path.dart_::_get_context ]
[dart     : sp(0x7f9d3667e5f8) fp(0x7f9d3667e610) pc(0x7f9d3c6aec82) package:path/path.dart_::_dirname ]
[dart     : sp(0x7f9d3667e620) fp(0x7f9d3667e6a8) pc(0x7f9d3c6a6cc5) file:///b/s/w/ir/tests/standalone_2/io/socket_sigpipe_test.dart_::_main__async_op ]
[dart     : sp(0x7f9d3667e6b8) fp(0x7f9d3667e6d8) pc(0x7f9d3c6a5f96) file:///b/s/w/ir/tests/standalone_2/io/socket_sigpipe_test.dart_::_main ]
[dart     : sp(0x7f9d3667e6e8) fp(0x7f9d3667e700) pc(0x7f9d3c6a5bfe) file:///b/s/w/ir/tests/standalone_2/io/socket_sigpipe_test.dart_::_main_main ]
[dart     : sp(0x7f9d3667e710) fp(0x7f9d3667e760) pc(0x7f9d3c6a5b12) dart:core__Closure@0150898_dyn_call ]
[dart     : sp(0x7f9d3667e770) fp(0x7f9d3667e798) pc(0x7f9d3c6a48e5) dart:isolate_::__delayEntrypointInvocation@1026248_<anonymous closure> ]
[dart     : sp(0x7f9d3667e7a8) fp(0x7f9d3667e800) pc(0x7f9d3c6a4655) dart:core__Closure@0150898_dyn_call ]
[dart     : sp(0x7f9d3667e810) fp(0x7f9d3667e840) pc(0x7f9d3c6a3ec0) dart:isolate__RawReceivePortImpl@1026248__handleMessage@1026248 ]
[entry    : sp(0x7f9d3667e850) fp(0x7f9d3667e8b8) pc(0x7f9d42502c9d)]

--- Re-run this test:
python3 tools/test.py -n dartk-reload-linux-debug-x64 standalone_2/io/socket_sigpipe_test
```

https://dart-ci.appspot.com/log/vm-kernel-reload-linux-debug-x64/dartk-reload-linux-debug-x64/9175/standalone_2/io/socket_sigpipe_test
https://dart-ci.appspot.com/log/vm-kernel-reload-linux-debug-x64/dartk-reload-linux-debug-x64/9175/standalone_2/io/socket_connect_stacktrace_test
https://dart-ci.appspot.com/log/vm-kernel-reload-linux-debug-x64/dartk-reload-linux-debug-x64/9175/standalone_2/io/file_system_watcher_large_set_test/0

**Comment by alexmarkov** [comment]
Bisected to 43c00097c2993de68a56d06cd780b228e77d283d. /cc @johnniwinther 

@rmacnak-google Is it a pre-existing bug, uncovered by that change?

**Comment by alexmarkov** [comment]
The following happens in this case:

(1) Constructor Context._internal() is called. By that time a fresh instance of `Context` class is created:

```dart
  Context._internal()
      : style = Style.platform as InternalStyle,
        _current = null;
```

(2) The constructor calls `Style.platform` which has a static initializer.
(3) Hot reload is triggered while static initializer is executed.

By that time, a `Context` instance still has its field

```dart
  final InternalStyle style;
```

not initialized, so it contains `null`.

During hot reload, when migrating fields in `CheckValueType` (in isolate_reload.cc), the field value (`null`) is tested against the type (non-nullable `InternalStyle`) and that check fails, which triggers an assertion.

It seems like this assertion is too strict and incompatible types can happen even for identity reload. We should probably relax the assertion to allow `null` values. @rmacnak-google WDYT?

**Comment by alexmarkov** [comment]
Possible fix: https://dart-review.googlesource.com/c/sdk/+/209161
