### ISSUE TITLE
Exception while renaming a member in an extension

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#41997]
I was attempting to rename one of the extension members in `pkg/analysis_server/lib/src/utilities/extensions`, though I don't remember now which one (and I manually renamed it). The following error was reported:

## Dart analysis issue

NoSuchMethodError: The getter 'length' was called on null.

## Version information

- Dart SDK 2.9.0-edge.6f8d67cf1a6b790ef564192bffe29d11f47c06e9
- Dart IntelliJ 201.7223.99
- IntelliJ IDEA 2020.1.1
- Mac OS X 10.15.3

## Details

NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _StringBase.compareTo (dart:core-patch/string_patch.dart:292:29)
#2      defaultCompare.<anonymous closure> (package:collection/src/utils.dart:15:48)
#3      binarySearch (package:collection/src/algorithms.dart:25:23)
#4      _IndexRequest.getStringId (package:analyzer/src/dart/analysis/search.dart:871:12)
#5      _IndexRequest.getElementUnitMemberId (package:analyzer/src/dart/analysis/search.dart:816:16)
#6      _IndexRequest.findElementId (package:analyzer/src/dart/analysis/search.dart:750:24)
#7      Search._addResultsInFile (package:analyzer/src/dart/analysis/search.dart:288:31)
<asynchronous suspension>
#8      Search._addResults (package:analyzer/src/dart/analysis/search.dart:272:15)
<asynchronous suspension>
#9      Search._searchReferences_Field (package:analyzer/src/dart/analysis/search.dart:350:13)
#10     Search.references (package:analyzer/src/dart/analysis/search.dart:88:14)
<asynchronous suspension>
#11     SearchEngineImpl.searchReferences (package:analysis_server/src/services/search/search_engine_internal.dart:102:41)
#12     _ExtensionMemberValidator._prepareReferences (package:analysis_server/src/services/refactoring/rename_extension_member.dart:198:26)
#13     _ExtensionMemberValidator.validate (package:analysis_server/src/services/refactoring/rename_extension_member.dart:130:11)
#14     RenameExtensionMemberRefactoringImpl.checkFinalConditions (package:analysis_server/src/services/refactoring/rename_extension_member.dart:51:23)
#15     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart:939:39)
<asynchronous suspension>
#16     _RefactoringManager.getRefactoring.<anonymous closure> (package:analysis_server/src/edit/edit_domain.dart)
#17     _rootRun (dart:async/zone.dart:1190:13)
#18     _CustomZone.run (dart:async/zone.dart:1093:19)
#19     _runZoned (dart:async/zone.dart:1630:10)
#20     runZonedGuarded (dart:async/zone.dart:1618:12)
#21     _RefactoringManager.getRefactoring (package:analysis_server/src/edit/edit_domain.dart:908:5)
#22     EditDomainHandler._getRefactoring (package:analysis_server/src/edit/edit_domain.dart:795:24)
#23     EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:361:16)
#24     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:241:40)
#25     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#26     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:237:50)
#27     _rootRun (dart:async/zone.dart:1190:13)
#28     _CustomZone.run (dart:async/zone.dart:1093:19)
#29     _runZoned (dart:async/zone.dart:1630:10)
#30     runZonedGuarded (dart:async/zone.dart:1618:12)
#31     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:236:5)
#32     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:169:16)
#33     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#34     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:159:47)
#35     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:104:26)
#36     _rootRunUnary (dart:async/zone.dart:1198:47)
#37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#44     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#45     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#46     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#48     _rootRunUnary (dart:async/zone.dart:1198:47)
#49     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#53     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
#54     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#55     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#56     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#57     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#58     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#59     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#60     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
#61     _rootRunUnary (dart:async/zone.dart:1198:47)
#62     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#63     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#66     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#67     _StreamController._add (dart:async/stream_controller.dart:655:7)
#68     _StreamController.add (dart:async/stream_controller.dart:597:5)
#69     _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#70     _rootRunUnary (dart:async/zone.dart:1206:13)
#71     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#72     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#73     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#74     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#75     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#76     _StreamController._add (dart:async/stream_controller.dart:655:7)
#77     _StreamController.add (dart:async/stream_controller.dart:597:5)
#78     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#79     _Closure.call (dart:core-patch/function.dart)
#80     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
#81     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#82     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#83     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#84     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## Debug log

```
1589921537235 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1589921537239 <= {"event":"analysis.implemented","params":{"file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.dart","classes":[],"members":[]...
1589921543652 => {"id":"30081","method":"edit.getAssists","params":{"file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.dart","offset":37465,"...
1589921543660 <= {"id":"30081","result":{"assists":[]}}
1589921547419 => {"id":"30082","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.da...
1589921547424 <= {"id":"30082","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":37465,"length":11,"elementKindName":"field","oldName":"shortString"}}}
1589921548836 => {"id":"30083","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.da...
1589921548837 <= {"id":"30083","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":37465,"length":11,"elementKindName":"field","oldName":"shortString"}}}
1589921548910 => {"id":"30084","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.da...
1589921548911 <= {"id":"30084","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":37465,"length":11,"elementKindName":"field","oldName":"shortString"}}}
1589921549182 => {"id":"30085","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.da...
1589921549183 <= {"id":"30085","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":37465,"length":11,"elementKindName":"field","oldName":"shortString"}}}
1589921549302 => {"id":"30086","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.da...
1589921549303 <= {"id":"30086","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":37465,"length":11,"elementKindName":"field","oldName":"shortString"}}}
1589921549627 => {"id":"30087","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.da...
1589921549628 <= {"id":"30087","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":37465,"length":11,"elementKindName":"field","oldName":"shortString"}}}
1589921549788 => {"id":"30088","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.da...
1589921549789 <= {"id":"30088","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":37465,"length":11,"elementKindName":"field","oldName":"shortString"}}}
1589921549867 => {"id":"30089","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.da...
1589921549868 <= {"id":"30089","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":37465,"length":11,"elementKindName":"field","oldName":"shortString"}}}
1589921550063 => {"id":"30090","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.da...
1589921550064 <= {"id":"30090","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":37465,"length":11,"elementKindName":"field","oldName":"shortString"}}}
1589921550157 => {"id":"30091","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.da...
1589921550158 <= {"id":"30091","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":37465,"length":11,"elementKindName":"field","oldName":"shortString"}}}
1589921550288 => {"id":"30092","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.da...
1589921550289 <= {"id":"30092","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":37465,"length":11,"elementKindName":"field","oldName":"shortString"}}}
1589921550419 => {"id":"30093","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.da...
1589921550420 <= {"id":"30093","result":{"initialProblems":[],"optionsProblems":[],"finalProblems":[],"feedback":{"offset":37465,"length":11,"elementKindName":"field","oldName":"shortString"}}}
1589921551426 => {"id":"30094","method":"edit.getRefactoring","params":{"kind":"RENAME","file":"/Users/brianwilkerson/src/dart/sdk/sdk/pkg/analysis_server/tool/completion_metrics/completion_metrics.da...
1589921551456 <= {"id":"30094","error":{"code":"SERVER_ERROR","message":"NoSuchMethodError: The getter 'length' was called on null.\nReceiver: null\nTried calling: length","stackTrace":"#0      Object...
```

**Comment by bwilkerson** [comment]
@scheglov

**Comment by scheglov** [comment]
This is probably a regression after af1ba835da91c88caa6b2ee67aebafe8f1053d48.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/148780
