### ISSUE TITLE
Enhanced enums: incorrect missing case clause analyzer warning

### ISSUE THREAD

**Issue by olof-dev** [dart-lang/sdk#49188]
The analyzer raises the warning `missing_enum_constant_in_switch` for the code below, saying `Missing case clause for 'data'` and similarly for `moreData`. Of course, they shouldn't have case clauses.

```dart
enum E {
  a, b;
  
  static final data = "I'm not a real enum member";
  static const moreData = 'Neither am I';
  
  String get name {
    switch(this) {
      case a:
        return 'AAAA';
      case b:
        return 'BBBB';
    }
  }
}
```

(Dart SDK version: 2.17.1 (stable))

**Comment by bwilkerson** [comment]
@scheglov @srawlins 

I confirmed that this is still happening on head.

Also note the unfortunate "potentially non-nullable" for the diagnostic on `name`. We should consider dropping the "potentially" when there's no question about nullability.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/247421

**Comment by mono0926** [comment]
@olof-dev 

The code example is missing `E.`. 
The following should be correct:

```dart
enum E {
  a, b;
  
  static final data = "I'm not a real enum member";
  static const moreData = 'Neither am I';
  
  String get name {
    switch(this) {
      case E.a:
        return 'AAAA';
      case E.b:
        return 'BBBB';
    }
  }
}
```

**Comment by olof-dev** [comment]
@mono0926 Thanks for the input. The issue is not that the code doesn't run, but rather about an incorrect analyzer warning about missing case clauses for `data` and `moreData`. If you test your code sample e.g. on [dartpad.dev](dartpad.dev) you'll see the analyzer warning.

**Comment by mono0926** [comment]
@olof-dev 

I think I understand your intention.
I then pointed out that the case specification contains another error that is confusing.
In the current code, removing the static field as shown below also results in a compile error:

```dart
enum E {
  a, b;
  
  String get name {
    switch(this) {
      case a: // `E.a` is correct
        return 'AAAA';
      case b: // `E.b` is correct
        return 'BBBB';
    }
  }
}
```

**Comment by olof-dev** [comment]
Ah sorry, now I understand what you mean. Just to be clear, I don't think it's the sample code that is incorrect: inside the enum definition, `a` resolves to `E.a`. The thing that's incorrect is the analyzer error shown in your screenshot. I think @scheglov's fix (see above) takes care of this too, but I didn't look very closely.

**Comment by scheglov** [comment]
Yes, the fix covers exactly this issue - understanding of usage of just simple identifiers in `case` for `switch` exhaustiveness.

**Comment by mono0926** [comment]
@olof-dev @scheglov 

I've confirmed that this bug has been fixed in Dart 2.17.5 included with the latest stable v3.0.3 of Flutter, and that the code of  https://github.com/dart-lang/sdk/issues/49188#issue-1262462056 works fine without any warnings.
I think this Issue should be closed.

DartPad: https://dartpad.dev/?id=caa4217a7363edd4b8ea3299cbdfdc48

**Comment by scheglov** [comment]
Thank you for the confirmation.

**Comment by olof-dev** [comment]
Confirmation from here too. Thanks for the quick fix!

**Comment by Levi-Lesches** [comment]
Hate to say but I don't think this is fixed: 
```dart
enum E {
  a, b;
  
  static final data = "I'm not a real enum member";
  static const moreData = 'Neither am I';
  // NEW CODE
  static const otherData = E.a;  // not a new entry in E
  
  String get name {
    switch(this) {
      case E.a:
        return 'AAAA';
      case E.b:
        return 'BBBB';
    }
  }
}
```
In this case, the analyzer doesn't complain, but the code doesn't compile on Dart 2.18.6 either: 
```
Error compiling to JavaScript:
Info: Compiling with sound null safety
lib/main.dart:12:14:
Error: A non-null value must be returned since the return type 'String' doesn't allow null.
  String get name {
             ^
Error: Compilation failed.
```
It's worth noting that adding `case E.otherData: return "CCCC";` works as intended: only "AAAA" is returned and the `E.otherData` case is skipped, but the analyzer complains of a duplicate case.

**Comment by srawlins** [comment]
Thanks for checking @Levi-Lesches . Confirmed on https://dartpad.dev/?channel=beta. The code analyzes cleanly and compiles.
