### ISSUE TITLE
Dartium 1.18.1 with package:js resolves to error (dartium, js-interop)

### ISSUE THREAD

**Issue by jakuub** [dart-lang/sdk#27047]
When we try to use package:js in dartium 1.18.1 it resolves to error with static method.

**Steps to reproduce**
1. clone https://github.com/jakuub/js-interop-dartium-exception.git
2. run pub get and pub serve
3. open http://localhost:8080/auth0.html in dartium (version 1.17 or 1.18.1)

**Throwned error**

```
Exception: No static method 'Auth0Settings.' declared in class 'Auth0Settings'.

NoSuchMethodError: method not found: 'Auth0Settings.'
Receiver: Type: class 'Auth0Settings'
Arguments: [...]
```

**Environment**

_OS_: Ubuntu linux and Arch linux (Manjaro)
_browser_: dartium 1.18.1 (and tried also with 1.17.0) downloaded from https://www.dartlang.org/install/archive
_uname -a_: Linux masina 4.4.15-3-MANJARO #1 SMP PREEMPT Mon Jul 11 19:04:26 UTC 2016 x86_64 GNU/Linux

I will be very happy if I am only doing somethin wrong, but I can't find out what and it works on Dartium 1.13.0

**Comment by jacob314** [comment]
You need to add 
@JS()
to the top of each library that uses JS interop.

That requirement was added to dartium in 1.18 to speedup dartium startup for large applications.

**Comment by jakuub** [comment]
Thank you very much, I didn't notice it in package:js documentation, maybe because it works before, but now I can see, it's there. 
Thank you very much, it fixes our problem.
