### ISSUE TITLE
Extension method throws error when called on null, even when the type is correct

### ISSUE THREAD

**Issue by pennzht** [dart-lang/sdk#44229]
## Environment
* Dart SDK version: **2.12.0-15.0.dev**
    - This issue exists on **2.12.0-15.0.dev** (dev) (Tue Nov 3 04:19:45 2020 -0800) on "macos_x64"
    - This issue does **NOT** exist on **2.12.0-3.0.dev** (dev) (Fri Oct 30 02:33:04 2020 -0700) on "macos_x64"
* OS: macOS Catalina 10.15.6

## How to reproduce
1. Switch the Dart SDK version to **2.12.0-15.0.dev** (flutter commit *bf94fa072d4eca3e9ebcecde044874384b157f0c*)
2. Run the dart program shown below.
3. The following error is thrown when running the marked line:
    * NoSuchMethodError: The getter 'isNull' was called on null.
    * (See below for full output)
4. Now, switch the SDK version to **2.12.0-3.0.dev** (flutter commit *c985fd35cd94a04371d70b91a38db54a3a7d7ee6*)
5. Run the same program.
6. The program finishes with the correct output.

## Program
```dart
extension ObjectBasics on Object? {
  bool get isNull => this.runtimeType == Null;
}

void main(){
  int? a;
  Object? b;
  var c;

  print (a);
  print (b);
  print (c);
  print ('====');

  print (a.runtimeType);
  print (b.runtimeType);
  print (c.runtimeType);
  print ('====');

  print (a.isNull);
  print (b.isNull); 
  print (c.isNull); // Error
  print ('====');
}
```

## Incorrect output (2.12.0-15.0.dev)
```
null
null
null
====
Null
Null
Null
====
true
true
Unhandled exception:
NoSuchMethodError: The getter 'isNull' was called on null.
Receiver: null
Tried calling: isNull
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      main (file:///Users/tianguang/Desktop/extension_test.dart:22:12)
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:311:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

## Expected output (2.12.0-3.0.dev)
```
null
null
null
====
Null
Null
Null
====
true
true
true
====
```

**Comment by lrhn** [comment]
This is expected and intended behavior.

The static type of `c` is `dynamic`, and `dynamic` is assumed to have *all* members, including `isNull`. Because of that, the extension method does not apply to `c`.

If we didn't do that, then code like:
```dart
class C {
  final Object? value;
  C(this.value);
  bool get isNull => value == null;
}
...
  var c;
  c = C(42);
  print(c.isNull);  // should print false
```
would be *changed* by introducing your extension. The extension method feature is designed such that instance members always take precedence, and for `dynamic` that means that extension methods can never apply.

**Comment by johnniwinther** [comment]
We recently fix a bug where, in opt-in libraries, we would resolve extension members on dynamic receivers: https://dart-review.googlesource.com/c/sdk/+/169340

**Comment by lrhn** [comment]
That explains it working in 3.0.dev. Thanks.

**Comment by pennzht** [comment]
@lrhn @johnniwinther 

Thank you very much for your help!
