### ISSUE TITLE
Non-copying BytesBuilder fails on adding non-typed List

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/sdk#26772]
```dart
import 'dart:io';

void main() {
  var builder = new BytesBuilder(copy: false);
  builder.add([0]);
}
```
```
Unhandled exception:
The null object does not have a getter 'length'.

NoSuchMethodError: method not found: 'length'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _BytesBuilder.add (dart:io/bytes_builder.dart:166)
```

Looks like [`_BytesBuilder.add`](https://github.com/dart-lang/sdk/blob/86fd2b62d15cfdfa148e14bbd429c24d041d6008/sdk/lib/io/bytes_builder.dart#L158-L167) is broken after https://github.com/dart-lang/sdk/commit/86fd2b62d15cfdfa148e14bbd429c24d041d6008

**Comment by lrhn** [comment]
Indeed, a bug on line 163.

**Comment by lrhn** [comment]
Fix landed on bleeding edge.
