### ISSUE TITLE
The null object does not have a method 'getDependencies'

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/sdk#23672]
In fletchc we see an error after updating to 1.11.0-dev.5.2 (aka 23736d3630da614c655d0569e1ba5af2021b1c61):

```
The null object does not have a method 'getDependencies'.

NoSuchMethodError: method not found: 'getDependencies'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      DeferredLoadTask._mapConstantDependencies (package:compiler/src/deferred_load.dart:410:14)
#3      DeferredLoadTask._mapDependencies (package:compiler/src/deferred_load.dart:464:9)
#4      DeferredLoadTask._mapDependencies (package:compiler/src/deferred_load.dart:455:9)
#5      DeferredLoadTask._mapDependencies (package:compiler/src/deferred_load.dart:455:9)
#6      DeferredLoadTask._mapDependencies (package:compiler/src/deferred_load.dart:455:9)
#7      DeferredLoadTask.onResolutionComplete.<anonymous closure> (package:compiler/src/deferred_load.dart:617:9)
#8      CompilerTask.measure (package:compiler/src/compiler.dart:2180:37)
#9      CompilerTask.measureElement.<anonymous closure> (package:compiler/src/compiler.dart:2198:48)
#10     Compiler.withCurrentElement (package:compiler/src/compiler.dart:907:15)
#11     CompilerTask.measureElement (package:compiler/src/compiler.dart:2198:14)
#12     DeferredLoadTask.onResolutionComplete (package:compiler/src/deferred_load.dart:607:5)
#13     Compiler.compileLoadedLibraries (package:compiler/src/compiler.dart:1643:22)
#14     Compiler.runCompiler.<anonymous closure> (package:compiler/src/compiler.dart:1510:7)
#15     _rootRunUnary (dart:async/zone.dart:911)
#16     _CustomZone.runUnary (dart:async/zone.dart:811)
#17     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#18     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#19     _Future._completeWithValue (dart:async/future_impl.dart:368)
#20     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#21     _rootRun (dart:async/zone.dart:904)
#22     _CustomZone.run (dart:async/zone.dart:803)
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:736)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#25     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

I believe this is a bug in dart2js, as it asks the backend for a constant before the backend has been allowed to determine if the constants are needed (notice this is called after resolution, but before codegen).

**Comment by skabet** [comment]
No longer seeing this.
