### ISSUE TITLE
History.replaceState(List) broken on Dartium (SDK 1.13), but fine on JS

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/sdk#24981]
The following code doesn't run after upgrading from 1.12.2 to 1.13:

```
window.history.replaceState([1, 'IyE2561gwSsABsVjJkX7XFX0', 1, 0, 10, null, null]);
```

However, it does work if compiling it to JS (tested  on Chrome).

**Comment by alan-knight** [comment]
That method has two required arguments, so the code in here fails for me in dart2js with a "t1 && C.History_methods).replaceState$1 is not a function". 

However, if you add the second parameter, it fails in Dartium 1.13 with the error that an object could not be cloned. It works in bleeding edge. The issue is that it's not doing the correct conversion. A workaround is to do the conversion manually.

      import 'dart:html_common' as common;
     ...
      window.history.replaceState(common.convertDartToNative_SerializedScriptValue([1, 'IyE2561gwSsABsVjJkX7XFX0', 1, 0, 10, null, null]), "stuff");

You may have to do an inverse operation on the popState event. That would be convertNativeToDart_SerializedScriptValue

**Comment by alan-knight** [comment]
Fix is https://codereview.chromium.org/1414903007/

**Comment by tomyeh** [comment]
Sorry, my bad. I didn't copy the code to this issue correctly. It shall be 

    window.history.replaceState([1, 'IyE2561gwSsABsVjJkX7XFX0', 1, 0, 10, null, null], title, url);

Great to know it was fixed.

**Comment by tomyeh** [comment]
Is it fixed in 1.13.1? My test code still can't run on the Dartium shipped in 1.13.1.

**Comment by alan-knight** [comment]
No, it's fixed in bleeding edge, and I presume dev at this point, but it isn't cherry-picked into 1.13.1

**Comment by tomyeh** [comment]
Got it. Thanks.
