### ISSUE TITLE
dartanalyser in WebStorm breaks for one specific project in 1.25.0-dev.9.0 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/sdk#30333]
See also https://youtrack.jetbrains.com/issue/WEB-28189

**Comment by zoechi** [comment]
I just tried `1.25.0-dev.10.0` with the same result.
I'm still stuck on `1.25.0-dev.8.0` to get analysis results in my project.

**Comment by bwilkerson** [comment]
Are there steps I can take to try to reproduce the problem?

**Comment by zoechi** [comment]
@bwilkerson I just got an event in IntelliJ where clicking the link opened https://github.com/dart-lang/sdk/issues/new, but the content was just added to the URL bar instead of the input field as usual, this is why the content below is truncated. Not sure if this is of any help.
I don't know how to reliably reproduce this event. I played a bit around to see if something changes, and then the event popped up. 
```
https://github.com/dart-lang/sdk/issues/new?body=Analyzer%20Feedback%20from%20IntelliJ# Version information- `IDEA IU-172.3544.35`- `1.25.0-dev.9.0`- `IU-172.3544.35, JRE 1.8.0_152-release-915-b6x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1920x1200, 3360x1890  Retina`# ExceptionPlease append the contents of:file:///private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/report.txt```Dart analysis server, SDK version 1.25.0-dev.9.0, server version 1.18.3, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [/Users/zoechi/dart/bwu_product/bwu_product_server], excluded: [/Users/zoechi/dart/bwu_product/bwu_product_server/.idea, /Users/zoechi/dart/bwu_product/bwu_product_server/.pub, /Users/zoechi/dart/bwu_product/bwu_product_server/build]}, clientRequestTime: 1502904017856}NoSuchMethodError: The method 'configure' was called on null.Receiver: nullTried calling: configure(analysisOptions: Instance of 'AnalysisOptionsImpl', sourceFactory: Instance of 'SourceFactoryImpl')#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)#2      ContextManagerImpl._checkForPackagespecUpdate (package:analysis_server/src/context_manager.dart:926)#3      ContextManagerImpl._handleWatchEvent (package:analysis_server/src/context_manager.dart:1407)#4      _rootRunUnary (dart:async/zone.dart:1128)#5      _CustomZone.runUnary (dart:async/zone.dart:1012)#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)#9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)#10     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98)#11     _Forwardi
```

I added you as collaborator to the project on GitHub https://github.com/zoechi/bwu_product.
If you check it out and open the project root folder or the `bwu_product_server` directory, you should be able to reproduce the behavior where no analyzer results are shown.

**Comment by bwilkerson** [comment]
@zoechi Thanks!

https://codereview.chromium.org/3001023002/

**Comment by zoechi** [comment]
@bwilkerson curious what was special with this project to cause this issue?

**Comment by bwilkerson** [comment]
I don't know. I got to the point of realizing that we start watching the file system before creating the analysis driver and that therefore it's possible for the driver to be `null` in the methods that handle watch events, and didn't look to see what, if anything, might have made this project different.

**Comment by zoechi** [comment]
@bwilkerson thanks. I just saw that you didn't even need to check out my project.

**Comment by zoechi** [comment]
Is it possible this is still not included in 1.25.0-dev.13.0 ?

**Comment by bwilkerson** [comment]
If I follow the link to the code review, look for the link following "Committed:" and follow that, I can see that the commit was included in both 1.25.0-dev.13.0 and 1.25.0-dev.12.0. If it's still not working, then we should re-open this issue.

**Comment by zoechi** [comment]
I'm not sure if it's the same issue. The behavior is a bit different. But AFAIR there were a Dart-plugin update in the meantime.

I get

```
https://github.com/dart-lang/sdk/issues/new?body=Analyzer%20Feedback%20from%20IntelliJ# Version information- `IDEA IU-172.3757.52`- `1.25.0-dev.8.0`- `IU-172.3757.52, JRE 1.8.0_152-release-915-b10x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.12.6 unknown, screens 1920x1200, 3360x1890  Retina`# ExceptionPlease append the contents of:file:///private/var/folders/k0/l96hhr317hgcfkw1p58qzr880000gp/T/report1.txt```Dart analysis server, SDK version 1.25.0-dev.8.0, server version 1.18.3, error: Exception while using a Visitor to visit a FormalParameterListImpl in GenericFunctionTypeImpl in SimpleFormalParameterImpl in DefaultFormalParameterImpl in FormalParameterListImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImplNoSuchMethodError: The getter 'name' was called on null.Receiver: nullTried calling: name#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)#2      Visitor.checkIdentifier (package:linter/src/rules/non_constant_identifier_names.dart:48)#3      Visitor.visitFormalParameterList.<anonymous closure> (package:linter/src/rules/non_constant_identifier_names.dart:61)#4      Object&ListMixin.forEach (dart:collection/list.dart:63)#5      Visitor.visitFormalParameterList (package:linter/src/rules/non_constant_identifier_names.dart:59)#6      FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4811)#7      ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2756)#8      List.forEach (dart:core-patch/growable_array.dart:267)#9      ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2754)#10     UnifyingAstVisitor.visitFormalParameterList (package:analyzer/dart/ast/visitor.dart:3020)#11     FormalParameterListImpl.accept (pac
```
in Dart 1.25.0-dev.13.0 (the same in dev 11, 10, 9) 
but works fine in Dart 1.25.0-dev.8.0 

(not sure what broke the `Open issue submission form?` link in IntelliJ, since a while I only get the truncated content of the issue report in the URL bar. Perhaps it is only with this specific error. I didn't have others since a while)

**Comment by zoechi** [comment]
I'm not sure what version exactly I got above output (I forgot that I switched Dart versions several times and didn't pay attention at what version the event was added to the "Event Log" window).

With Dart 1.25.0-dev.13.0 currently no imports are recognized and I get a weird error at the `library` declaration

![image](https://user-images.githubusercontent.com/405837/29675105-70793f52-88f4-11e7-935d-9ffe3270137a.png)

**Comment by zoechi** [comment]
Sorry, the `library` declaration was my fault. 

After deleting the `~/.dartServer` directory. I got a lot less of the unrecognized imports.
But after opening different files, the list in the "Dart Analysis" window is growing again.
The error just don't come up immediately after restarting the analyzer.

**Comment by bwilkerson** [comment]
So just to be clear, I think this is the behavior you're seeing. When you open IntelliJ (or restart server directly), you get a few diagnostics that are not valid, but as you write code the number of invalid diagnostics increases. Do I have that right?

If so, are they increasing monotonically, or do they sometimes go away and then come back again?

**Comment by zoechi** [comment]
I think this is just the on-disk cache that wasn't filled immediately. After having opened more and more files, the list of errors grew to until all files of one of the 3 projects were listed, and than stayed the same. After restarting the analysis server the full list appears immediately, the same as before I deleted the disk cache. (the errors are all invalid and go away when I switch back to dev-8)

**Comment by bwilkerson** [comment]
Are all / most of the invalid errors related to URI resolution (which would include things like undefined names that would have been defined if URIs had been resolved correctly)? If so, are they all `package:` URIs?

If so, can you check that there are `.packages` files where you'd expect them at check one of two of the unresolved URIs to see whether the package location is correct in the `.packages` file?

**Comment by zoechi** [comment]
Yes, it's only package imports. Relative imports are recognized.
The packages file points to the right directory. It also is working perfectly fine once I switch back to dev-8.
