### ISSUE TITLE
fullscreen api js bindings do not work 

### ISSUE THREAD

**Issue by muth02446** [dart-lang/sdk#25324]
I am using this piece of dart code:

void ToggleFullscreen() {
  if (document.fullscreenElement == null) {
    document.documentElement.requestFullscreen();
  } else {
    document.exitFullscreen();
  }
}

but the transpiled code gives this message on the JS console (for chrome 47):

Uncaught TypeError: document.documentElement.requestFullscreen is not a function

This probably needs to implemented a little more defensively to work on multiple browsers, c.f.:
http://www.sitepoint.com/use-html5-full-screen-api/

**Comment by zoechi** [comment]
See also

- https://github.com/dart-lang/sdk/issues/4136
- https://github.com/dart-lang/sdk/issues/25177

**Comment by kevmoo** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

**Comment by mnordine** [comment]
Sadly, this is still an issue. Just verified it still doesn't work with `2.60-dev.8.2`

**Comment by kevmoo** [comment]
@vsmenon ?

**Comment by mnordine** [comment]
This is still an issue. Does not work in at least Firefox and iOS. Relevant code in `html_dart2js.dart`:

```dart
  /**
   * Static factory designed to expose `fullscreenchange` events to event
   * handlers that are not necessarily instances of [Element].
   *
   * See [EventStreamProvider] for usage information.
   */
  @SupportedBrowser(SupportedBrowser.CHROME)
  @SupportedBrowser(SupportedBrowser.SAFARI)
  static const EventStreamProvider<Event> fullscreenChangeEvent =
      const EventStreamProvider<Event>('webkitfullscreenchange');
```

**Comment by mnordine** [comment]
@kevmoo Is there any documentation on how these IDL bindings work? I'd really like to pitch in and fix this up if I can.

**Comment by kevmoo** [comment]
@rakudrama and @srujzs would be the folks to ask...

**Comment by srujzs** [comment]
`webkitRequestFullscreen` doesn't exist in Firefox and `requestFullscreen` is available starting in v64 per MDN documentation, so I'm not surprised it's unsupported there. The former works for me in Safari v13.0.5, what version of Safari are you testing with?

Anyways, I think we need more than one definition here if we want to support all browsers. A complication here is breaking those who rely on the `requestFullscreen`->`webkitRequestFullscreen` binding. Alternatively, Stephen, is there a way to label multiple `JSName`s to a declaration? I'm assuming no.

@mnordine, thank you for volunteering to contribute, we appreciate it. Unfortunately, `dart:html` is complicated to contribute to since it's a combination of code generation and manually written code, and ends up requiring largely undocumented knowledge to navigate and fix many issues. I think this issue is no different. As a workaround, I think you can use `js_util` (haven't tested this), e.g. `js_util.callMethod(document.body, 'requestFullscreen', [])` and `js_util.promiseToFuture` on the result.

**Comment by mnordine** [comment]
> what version of Safari are you testing with?

I just tested on 13.1.2 on Mac OS, and it works there. It doesn't seem to be working on iPadOS 14 Public Beta 5. One interesting thing there is I have the `requestFullScreen()` triggered from a key event on desktop, but a touch event on iOS, so maybe something's wrong there, or maybe it's the beta. I don't have a stable release to test here right now.

> Alternatively, Stephen, is there a way to label multiple JSNames to a declaration?

Yeah, I was thinking there must be some way to define multiple prefixes?

> Unfortunately, `dart:html` is complicated to contribute to 

I'm ok with complicated, but I also understand where you're coming from. I'd just like to be able to contribute to a project that's given so much to me, and `dart:html` seems like it is broken in a lot of ways (especially newer APIs and functionality), and that's the area that interests me the most.

**Comment by srujzs** [comment]
That seems a little weird that `webkitRequestFullscreen` doesn't exist but `requestFullscreen` does.

> I was thinking there must be some way to define multiple prefixes
It doesn't seem like it's possible, but I'll wait for Stephen's response.

`dart:html` is at a complexity point where updating the source files which it uses is a tremendous effort, so unfortunately, that's going to continue being true for now. We're trying to reimagine `dart:html` (or `package:html`) to make it less nebulous and move away from the code gen that it currently has, so it'd hopefully be easier and more straightforward to contribute to.

**Comment by deepbluev7** [comment]
Has there been any progress on this? It would be nice, if we didn't have to rely on workarounds and it seems like the unprefixed method is supported everywhere but on Safari...

**Comment by srujzs** [comment]
I think we can fix this, since the API returns a Promise anyways, so you could argue it's broken today as it is, so it won't be breaking anyone. We can just create a method that checks for both bindings and update the signature to accept an options parameter as well. I have a CL, will update.
