### ISSUE TITLE
VM does not build with XCode 26.4 - readdir_r has been deprecated

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/sdk#63089]
```
../../runtime/bin/directory_macos.cc:111:7: error: 'readdir_r' is deprecated: This function cannot be used safely as it does not take into account the variability of {NAME_MAX}.  It is highly recommended that you use readdir(3) instead. [-Werror,-Wdeprecated-declarations]
  111 |       readdir_r(reinterpret_cast<DIR*>(lister_), &entry, &result));
      |       ^
sdk/xcode_links/MacOSX26.4.sdk/usr/include/dirent.h:114:1: note: 'readdir_r' has been explicitly marked deprecated here
  114 | __deprecated_msg("This function cannot be used safely as it does not take into account the variability of {NAME_MAX}.  It is highly recommended that you use readdir(3) instead.")
      | ^
sdk/xcode_links/MacOSX26.4.sdk/usr/include/sys/cdefs.h:227:48: note: expanded from macro '__deprecated_msg'
  227 |         #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
      |                                                       ^
../../runtime/bin/directory_macos.cc:271:28: error: 'readdir_r' is deprecated: This function cannot be used safely as it does not take into account the variability of {NAME_MAX}.  It is highly recommended that you use readdir(3) instead. [-Werror,-Wdeprecated-declarations]
  271 |   while (NO_RETRY_EXPECTED(readdir_r(dir_pointer, &entry, &result)) == 0) {
      |                            ^
sdk/xcode_links/MacOSX26.4.sdk/usr/include/dirent.h:114:1: note: 'readdir_r' has been explicitly marked deprecated here
  114 | __deprecated_msg("This function cannot be used safely as it does not take into account the variability of {NAME_MAX}.  It is highly recommended that you use readdir(3) instead.")
      | ^
sdk/xcode_links/MacOSX26.4.sdk/usr/include/sys/cdefs.h:227:48: note: expanded from macro '__deprecated_msg'
  227 |         #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
      |     
```
