### ISSUE TITLE
All Flutter try-bots crash with "Infra Failure" issue.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#51946]
See https://ci.chromium.org/ui/p/dart/builders/try/flutter-linux-debug-try/164/overview as example.
The error is:
```
 The recipe has crashed at point 'Uncaught exception'!
 Traceback (most recent call last):
   File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/engine.py", line 585, in run_steps
     raw_result = recipe_obj.run_steps(api, engine)
   File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/recipe_deps.py", line 931, in run_steps
     recipe_result = self.global_symbols['RunSteps'](*args)
   File "/b/s/w/ir/kitchen-checkout/flutter/recipes/engine_v2/builder.py", line 216, in RunSteps
     Build(api, checkout, env, env_prefixes, outputs)
   File "/b/s/w/ir/kitchen-checkout/flutter/recipes/engine_v2/builder.py", line 151, in Build
     deps = build.get('dependencies', [])
 AttributeError(''NoneType' object has no attribute 'get'')
```

**Comment by sortie** [comment]
cc @derekxu16 current gardener :)

**Comment by derekxu16** [comment]
Looks like the failures have changed from infra failures to build failures caused by https://github.com/dart-lang/sdk/commit/d1d232776addc2e4079e971fdb10b65cff70ef4c. I'll try to make a PR that fixes it.

**Comment by derekxu16** [comment]
Looks like we'll have to wait for https://github.com/dart-lang/sdk/commit/d1d232776addc2e4079e971fdb10b65cff70ef4c to reach the dev branch and then include a manual Dart SDK roll in https://github.com/flutter/engine/pull/40916.

cc @jonahwilliams @zanderso

**Comment by zanderso** [comment]
If https://github.com/dart-lang/sdk/commit/d1d232776addc2e4079e971fdb10b65cff70ef4c has any difficulty rolling into flutter/flutter or google3, it will put the branch cut at risk. Please consider reverting.

**Comment by eyebrowsoffire** [comment]
I believe it should roll into flutter/flutter and google3 without issue, but I can't be 100% sure. As far as I know, no code anywhere outside the dart SDK patch files and the dart2wasm compiler itself uses things from the `dart:wasm` library, so I am fairly confident it should be safe to remove from the `sky_engine` sources. I also am not certain that this change will resolve the issue that is blocking the dart -> engine roll, but my current understanding is that it will. This is difficult to locally validate how this will affect downstream.

**Comment by eyebrowsoffire** [comment]
Question for the dart stakeholders here: is it considered important for the `dart:wasm` ->`dart:_wasm` migration to happen before the branch cut?

**Comment by derekxu16** [comment]
I'm going to close this because the `dart:wasm` -> `dart:_wasm` migration issue has been resolved. The Flutter tryjobs are failing for a different reason now (dart:io class modifiers), and @brianquinlan is currently working on a fix for that.

cc current gardener @aam
