### ISSUE TITLE
get item from DataTransferItemList 

### ISSUE THREAD

**Issue by KudrMichal** [dart-lang/sdk#26435]
hi, 

problem with reading items from DataTransferItemList

print(dataTransfer.items);
print(dataTransfer.items.length);

prints corrent values:
[object DataTransferItemList]
1

dataTransfer.items[i]  throws error
type 'int' is not a subtype of type 'String' of 'name' where
  int is from dart:core
  String is from dart:core

I tried use a item(int index method) and it throws
: property is not a function

thanks

**Comment by zoechi** [comment]
Are you talking about https://api.dartlang.org/1.12.0/dart-html/DataTransferItem-class.html ?

It only has `kind`, type`, `getAsEntry`, `getAsFile`, `getAsString`

Can you please create an example in https://dartpad.dartlang.org/ that demonstrates what you try to accomplish and that allows to reproduce the problem?

**Comment by KudrMichal** [comment]
I need to get DataTransferItem from DataTransferItemList and then I need to call getAsEntry, something like this...

DataTransferItem item = dataTransfer.items[0];    //this fails in dart 1.16 (in 1.14 version it is OK)
Entry entry = item.getAsEntry();

throws 
type 'int' is not a subtype of type 'String' of 'name'

OK then... I tried this
DataTransferItem item = dataTransfer.items['0'];

throws 
type 'String' is not a subtype of type 'int' of 'index'

Like I said, in dart 1.14 it worked OK

Maybe bug?

Thanks
Michal

**Comment by jimmyshiau** [comment]
I try to print
```
input.onPaste.listen((ClipboardEvent e) {
      print(e.clipboardData.items.item(0));
    });
```
But I got this error with dart 1.16
```
[ws] Uncaught : property is not a function
#0      Blink_JsNative_DomException.callMethod (dart:_blink:23438)
#1      BlinkDataTransferItemList.item_Callback_1_ (dart:_blink:3545)
#2      DataTransferItemList.item (dart:html:9373)
```

**Comment by KudrMichal** [comment]
It looks like method item(int index) was removed.

**Comment by jimmyshiau** [comment]
It still not works with dart 1.17.1

**Comment by silvianacmp** [comment]
Any update on this? It seems like Dartium's implementation doesn't support this (simple) API:
```
class DataTransferItemList extends DartHtmlDomObject {
  ...
  DataTransferItem operator [](int index) {
    return _blink.Blink_JsNative_DomException.getProperty(this, index);
  }
```
(cc/ @ochafik )

**Comment by alan-knight** [comment]
There was a CL https://codereview.chromium.org/1431543004/ to fix this some time ago.
It seems like it isn't entirely working, although it's not clear to me. At least one of the uses here was trying to index via a string, which won't work.

**Comment by ochafik** [comment]
Definitely not fixed yet, in this chrome://version/:
```
Chromium	45.0.2454.104 (Developer Build) (64-bit)
Revision	67a7ba9669f7bb0300ef35085d4e6bb98b1966cc
OS	Linux 
Blink	537.36 (@abaaf1d0b6b6483140b5dca34e80fc259833ddf7)
JavaScript	V8 4.5.103.35
Dart	1.20.0-dev.0.0
```

The following `index.html`:
```html
<script type="application/dart">
  import 'dart:html';
  main() {
    document.body.onPaste.listen((ClipboardEvent e) {
      print(e.clipboardData.items.item(0));
    });
  }
</script>
```

Gives:
```
Uncaught Unhandled exception:
: property is not a function
#0      Blink_JsNative_DomException.callMethod (dart:_blink:23416)
#1      BlinkDataTransferItemList.item_Callback_1_ (dart:_blink:3544)
#2      DataTransferItemList.item (dart:html:9372)
#3      main.<anonymous closure> (file:///.../index.html:6:35)
```

While the other variant:
```html
<script type="application/dart">
  import 'dart:html';
  main() {
    document.body.onPaste.listen((ClipboardEvent e) {
      print(e.clipboardData.items[0]);
    });
  }
</script>
```

Gives:
```
Uncaught Unhandled exception:
type 'int' is not a subtype of type 'String' of 'name' where
  int is from dart:core
  String is from dart:core

#0      Blink_JsNative_DomException.getProperty (dart:_blink:23358)
#1      DataTransferItemList.[] (dart:html:9384)
#2      main.<anonymous closure> (file:///usr/local/google/home/ochafik/dartium-bug.html:6:34)
```

**Comment by ochafik** [comment]
And for the sake of completeness, here's the equivalent JavaScript which works:
```html
<script>
  setTimeout(function() { // execute when body exists
    document.body.onpaste = function(e) {
      console.log(e.clipboardData.items[0]);
    }
  }, 0);
</script>
```

**Comment by alan-knight** [comment]
Sigh. Yup, it was passing an int to JS when it needed to be a string. https://codereview.chromium.org/2326113002
