### ISSUE TITLE
SpeechSynthesis getVoices error  in html_dart2js

### ISSUE THREAD

**Issue by drpond1** [dart-lang/sdk#34350]
My code:     List<SpeechSynthesisVoice>  list = speechSynthesis.getVoices();

produces a runtime error of
TypeError
lib__drPondPicture.speechSynthesis[$getVoices] is not a function

No errors appear in the Dart Analyzer.  The speechSythesis variable is not null.
Worked in Dart 1.0

**Comment by vsmenon** [comment]
@terrylucas

**Comment by alexanderzeillinger** [comment]
Can confirm and still present in 2.1.0-dev.7.1

**Comment by alexanderzeillinger** [comment]
Also in 2.1.0-dev.8.0

**Comment by alexanderzeillinger** [comment]
Still broken in 2.1.0

**Comment by alexanderzeillinger** [comment]
No surprise, broken in 2.1.2-dev.0.0

**Comment by alexanderzeillinger** [comment]
Incredible - still broken in 2.3.2

**Comment by alexanderzeillinger** [comment]
No fix in 2.5.0 sadly.

As a workaround import "dart.js" and call the JS methods directly.
So instead of:

        List<SpeechSynthesisVoice> voices = window.speechSynthesis.getVoices();

        SpeechSynthesisUtterance utterance = new SpeechSynthesisUtterance(sentence);
        utterance.volume = volume;
        utterance.voice = voices[0];
        utterance.rate = speed;
        window.speechSynthesis.speak(utterance);

do this:

        var voices = context['speechSynthesis'].callMethod('getVoices');

        utterance = new JsObject(context['SpeechSynthesisUtterance'], [sentence]);
        utterance['volume'] = volume;
        utterance['voice'] = voices[0];
        utterance['rate'] = speed;
        context['speechSynthesis'].callMethod('speak', [utterance]);

**Comment by drpond1** [comment]
This works.   Thank you for your help.

**Comment by sma** [comment]
Still broken in 3.0.  Why is it so difficult to fix the declaration?
