### ISSUE TITLE
List.unmodifiable throwing errors in dart 1.11.3

### ISSUE THREAD

**Issue by DanielJoyce** [dart-lang/sdk#24001]
static final List<String> _fields = new List.unmodifiable(['foo','bar','qux'...]);

Code works fine in 1.11.0 and dartium. 

Using pub serve, I am seeing the following error

Uncaught Uncaught Error: NoSuchMethodError : method not found: 'Symbol("unmodifiable")'
Receiver: ""
Arguments: [Instance of 'JSArray']
Stack Trace:
NoSuchMethodError : method not found: 'Symbol("unmodifiable")'
Receiver: ""
Arguments: [Instance of 'JSArray']

**Comment by sethladd** [comment]
Can you please provide a stand-alone script that exhibits the issue? thanks!

**Comment by DanielJoyce** [comment]
Working on it. It works in several places in our code, but breaks in three areas. This a complex dart/polymer/chrome app. Might be a heisenbug somewhere. 

Switched to const[] to get around it for now.

**Comment by DanielJoyce** [comment]
It compiles to javascript just fine, the web browser logs the message once it tries to execute the resulting javascript.

**Comment by DanielJoyce** [comment]
Weird 'bug'. The code pushed/pulled data into/out of some indexeddb tables mapping properties to a map. Someone fatfingered a name, so a column no longer mapped properly to the name specified in _fields.

Once the tables were cleared, the bug went away.

But I can't see how bad data in a table would produce such a misleading exception.

**Comment by DanielJoyce** [comment]
Or why switching to const[] would fix it even with the bad data...
