### ISSUE TITLE
dart2js produces bad code after upgrading to 2.4.0

### ISSUE THREAD

**Issue by yoxel** [dart-lang/sdk#37489]
We have a AngularDart app that we compile with dart2js and its default optimizations.
After upgrading Dart to 2.4.0 the dart2js produced code started having runtime errors.

First problem seems to be related to the tree shaking. We get 

NoSuchMethodError: method not found: ‘get$records’ (emails.get$records is not a function)

on a class getter that should not be removed as it's used in the code alot.

```dart
abstract class RfQueryResult<T extends AbsCrmObject> extends AbsCrmObject {
  List<T> get records => getMethodValue<List>('records').cast<T>();
...
```

When debugging JS we don't find this getter. Also running dart2js with -O0 fixes the issue as the getter 'records' is preserved without the O1 optimizations.

Second problem is with maps where keys are supposed to be runtime types. In JS runtime the map lookups return nulls because the key values for some reason contain '<>', like 'Type<>' instead of 'Type'. So looking up by types does not find its entry.  See JS screenshot

https://gyazo.com/bff814296502c70062138894b751f00f

In Dart the map is Map<Type, Cacheable> cache = <Type, Cacheable>{};
In runtime cache[type] is called with type=LayoutCache but the map's key is 'LayoutCache<>' so null is returned. What is going on here?

For now we have to downgrade Dart back to 2.3.x

**Comment by vsmenon** [comment]
Hmm, these both sound like behaviors you should only see with `O2` and above (but usually a sign of a bug in the code).  Are you running via `webdev`?

Note, with `-O2` and above dart2js doesn't preserve type names (to reduce code size).  This shouldn't affect actual type equality, but it'll make it harder to debug / inspect.

fyi - @rakudrama @johnniwinther

**Comment by yoxel** [comment]
After encountering the first problem with removed getters (when using -O1) we switched to -O0 (no optimizations) and with that we're getting the map/key/type issues. We don't use webdev

Our build.yaml has

`build_web_compilers|entrypoint:
        generate_for:
          - web/office.dart
          - web/gmail.dart
          - web/rf-office.dart
          - web/rf-gmail.dart
          - test/**.browser_test.dart
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
            - -O0
            - --trust-primitives 
            - --omit-implicit-checks`

**Comment by rakudrama** [comment]
For the first problem, the missing `get$records` method, we will need more information. We need to get to a point where we can reproduce the problem to understand what is happening.
What do the methods with the call sites look like, in the original Dart and generated JavaScript?
Are you using any other dart2js command-line options?

For the map problem, the screenshot indicates that the entries in the map have keys that are `String`s. These won't match the `Type` keys. How are entries added to the map? Was there a `toString` operation somewhere?

One thing that stands out in the screenshot is the presence of `$ti: []`. This is a bit weird as it is explicitly storing zero type arguments. I have never seen an empty `$ti` array, either the type arguments are elided (a `-O1` optimization) and there is no array, or the array contains at least one type argument.  We need to figure out what might be causing this intermediate position.

Ways forward:
- Can you cut down your program into something smaller that has the same problem?
- Could you email me the outputs of compiling with `-O1` and `-O2` so I can look for other hints in the generated code?

**Comment by rakudrama** [comment]
I suspect the program has some bugs or inconsistencies hidden by using `--trust-primitives` and `--omit-implicit-checks`. Does your program run (on Dart 2.3.x) if you don't use these flags?

**Comment by yoxel** [comment]
I think we could create a reproducible test case for the map/type problem.

I am not sure how to go about the removed getters. What is strange is that that getter is accessed in different points in our code and only one point has this issue. I am not sure we will be able to create a reproducible small case.

**Comment by yoxel** [comment]
This is how various Cacheable classes are added to that map.
Is ... = {} the issue? We should probably do <Type, Cacheable>{}?

`Map<Type, Cacheable> cache = {};

  void registerCache(Cacheable cacheable) {
    cache[cacheable.runtimeType] = cacheable;
  }`

**Comment by yoxel** [comment]
We can't abandon those flags --trust-primitives and --omit-implicit-checks. There are just way too many issues highlighted that we can't even address because they're Angular/template related. We address what we can when we develop but then we use these flags when compiling for production. Let me turn the checks temporarily on to see this specific code.

**Comment by vsmenon** [comment]
Those flags mean you're effectively running in `O3` or `O4` (with just minification disabled).

In general, that's fine, but it means a higher testing threshold.  dart2js will tree-shake away based on the static type.  If you're omitting a check that would have failed at runtime, you'll see this behavior - a tree-shaken method that dart2js believes is unreachable due to static types.

You might run in dev mode with Chrome Dev Tools open and Pause on all exceptions (caught and uncaught).  Are any errors thrown?

**Comment by yoxel** [comment]
Why 2.3.x was not tree shaking those getters away and 2.4.0 started doing so?

**Comment by yoxel** [comment]
re: map/key, sorry the 1st screenshot was not correct. our developer started experimenting with String keys. This was the original situation:

https://i.gyazo.com/bed9b7358cabcc208784b393ee30b0ec.png

**Comment by vsmenon** [comment]
> Why 2.3.x was not tree shaking those getters away and 2.4.0 started doing so?

2.4 is a little more aggressive with tree shaking with `O3+` enabled.  It should preserve the behavior on correct (non-`Error` throwing) code.

**Comment by yoxel** [comment]
Thank you. Cleaning our implicit type casting more and will try dart2js again. Is there an explanation of all O1,2,3 optimizations? And which one is default these days?

**Comment by vsmenon** [comment]
We keep `dart2js -hv` (run from the command line) up-to-date.  It will describe the optimization levels.

**Comment by yoxel** [comment]
After cleaning many implicit casts in our code everything started to work fine.
Thank you
