### ISSUE TITLE
Can't build the Dart SDK on MacOS

### ISSUE THREAD

**Issue by Calin-Cosma** [dart-lang/sdk#45965]
Following the instructions here:
https://github.com/dart-lang/sdk/wiki/Building#source

I am getting

```
$ ./tools/build.py --no-goma --mode release --arch x64 create_sdk
Generating Xcode projects took 76ms
Done. Made 325 targets from 91 files in 1250ms
ninja -C xcodebuild/ReleaseX64 create_sdk
ninja: Entering directory `xcodebuild/ReleaseX64'
[1/3267] CXX obj/runtime/bin/standalone_dart_io_product.eventhandler_win.o
FAILED: obj/runtime/bin/standalone_dart_io_product.eventhandler_win.o 
../../buildtools/mac-x64/clang/bin/clang++ -MMD -MF obj/runtime/bin/standalone_dart_io_product.eventhandler_win.o.d -DTOOLCHAIN_VERSION=ZAE4SZ9wWxDuyLVSik3Q7Yhc8ZDHNWQGXrAy4wijvRsC -DNDEBUG -DTARGET_ARCH_X64 -DNDEBUG -DTARGET_OS_MACOS -DPRODUCT -I../../runtime -I../../third_party -I../.. -Igen -I../../runtime/include -I../../runtime -I../../runtime/include -I../../third_party/zlib -I../../third_party/boringssl/src/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.13  -fno-exceptions -arch x86_64 -fcolor-diagnostics -Wall -Wextra -Werror -Wendif-labels -Wno-missing-field-initializers -Wno-unused-parameter -Wno-tautological-constant-compare -Wpartial-availability -fdebug-prefix-map=/Users/calin/work/others/projects/dart/dart-sdk/sdk=../.. -no-canonical-prefixes -stdlib=libc++ -Wheader-hygiene -Wstring-conversion -O3 -fno-ident -fdata-sections -ffunction-sections -g3 -ggdb3 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -O3 -fvisibility=hidden -fvisibility-inlines-hidden -fno-omit-frame-pointer -std=c++17 -fno-rtti -fno-exceptions -c ../../runtime/bin/eventhandler_win.cc -o obj/runtime/bin/standalone_dart_io_product.eventhandler_win.o
In file included from ../../runtime/bin/eventhandler_win.cc:5:
In file included from ../../runtime/platform/globals.h:78:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/arpa/inet.h:71:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/netinet/in.h:538:2: error: unknown type name 'uint32_t'
        uint32_t                gr_interface;   /* interface index */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/netinet/in.h:543:2: error: unknown type name 'uint32_t'
        uint32_t                gsr_interface;  /* interface index */
        ^
```

Followed by a looong list of instances of the same error, and later on some other errors, like:

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/sys/resource.h:216:2: error: unknown type name 'uint8_t'
        uint8_t  ri_uuid[16];
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[7/3267] CXX obj/runtime/bin/standalone_dart_io_product.file_system_watcher.o
FAILED: obj/runtime/bin/standalone_dart_io_product.file_system_watcher.o 
../../buildtools/mac-x64/clang/bin/clang++ -MMD -MF obj/runtime/bin/standalone_dart_io_product.file_system_watcher.o.d -DTOOLCHAIN_VERSION=ZAE4SZ9wWxDuyLVSik3Q7Yhc8ZDHNWQGXrAy4wijvRsC -DNDEBUG -DTARGET_ARCH_X64 -DNDEBUG -DTARGET_OS_MACOS -DPRODUCT -I../../runtime -I../../third_party -I../.. -Igen -I../../runtime/include -I../../runtime -I../../runtime/include -I../../third_party/zlib -I../../third_party/boringssl/src/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=10.13  -fno-exceptions -arch x86_64 -fcolor-diagnostics -Wall -Wextra -Werror -Wendif-labels -Wno-missing-field-initializers -Wno-unused-parameter -Wno-tautological-constant-compare -Wpartial-availability -fdebug-prefix-map=/Users/calin/work/others/projects/dart/dart-sdk/sdk=../.. -no-canonical-prefixes -stdlib=libc++ -Wheader-hygiene -Wstring-conversion -O3 -fno-ident -fdata-sections -ffunction-sections -g3 -ggdb3 -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-private-field -Wnon-virtual-dtor -Wvla -Woverloaded-virtual -Wno-comments -g3 -ggdb3 -fno-rtti -fno-exceptions -Wimplicit-fallthrough -O3 -fvisibility=hidden -fvisibility-inlines-hidden -fno-omit-frame-pointer -std=c++17 -fno-rtti -fno-exceptions -c ../../runtime/bin/file_system_watcher.cc -o obj/runtime/bin/standalone_dart_io_product.file_system_watcher.o
In file included from ../../runtime/bin/file_system_watcher.cc:5:
In file included from ../../runtime/bin/file_system_watcher.h:9:
In file included from ../../buildtools/mac-x64/clang/bin/../include/c++/v1/stdlib.h:100:
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:773:12: error: no member named 'labs' in the global namespace; did you mean 'abs'?
  return ::labs(__x);
         ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:772:39: note: 'abs' declared here
inline _LIBCPP_INLINE_VISIBILITY long abs(long __x) _NOEXCEPT {
                                      ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:777:12: error: no member named 'llabs' in the global namespace
  return ::llabs(__x);
         ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:785:12: error: no member named 'fabsf' in the global namespace
  return ::fabsf(__lcpp_x);
         ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:789:12: error: no member named 'fabs' in the global namespace; did you mean 'abs'?
  return ::fabs(__lcpp_x);
         ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:772:39: note: 'abs' declared here
inline _LIBCPP_INLINE_VISIBILITY long abs(long __x) _NOEXCEPT {
                                      ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:794:12: error: no member named 'fabsl' in the global namespace
  return ::fabsl(__lcpp_x);
         ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:808:34: error: unknown type name 'ldiv_t'
inline _LIBCPP_INLINE_VISIBILITY ldiv_t div(long __x, long __y) _NOEXCEPT {
                                 ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:809:12: error: no member named 'ldiv' in the global namespace
  return ::ldiv(__x, __y);
         ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:812:34: error: unknown type name 'lldiv_t'
inline _LIBCPP_INLINE_VISIBILITY lldiv_t div(long long __x,
                                 ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:814:12: error: no member named 'lldiv' in the global namespace
  return ::lldiv(__x, __y);
         ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:822:93: error: no member named 'acosf' in the global namespace; did you mean 'acos'?
inline _LIBCPP_INLINE_VISIBILITY float       acos(float __lcpp_x) _NOEXCEPT       {return ::acosf(__lcpp_x);}
                                                                                          ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:822:46: note: 'acos' declared here
inline _LIBCPP_INLINE_VISIBILITY float       acos(float __lcpp_x) _NOEXCEPT       {return ::acosf(__lcpp_x);}
                                             ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:823:93: error: no member named 'acosl' in the global namespace; did you mean 'acos'?
inline _LIBCPP_INLINE_VISIBILITY long double acos(long double __lcpp_x) _NOEXCEPT {return ::acosl(__lcpp_x);}
                                                                                          ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:822:46: note: 'acos' declared here
inline _LIBCPP_INLINE_VISIBILITY float       acos(float __lcpp_x) _NOEXCEPT       {return ::acosf(__lcpp_x);}
                                             ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:829:38: error: call to 'acos' is ambiguous
acos(_A1 __lcpp_x) _NOEXCEPT {return ::acos((double)__lcpp_x);}
                                     ^~~~~~
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:822:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY float       acos(float __lcpp_x) _NOEXCEPT       {return ::acosf(__lcpp_x);}
                                             ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:823:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long double acos(long double __lcpp_x) _NOEXCEPT {return ::acosl(__lcpp_x);}
                                             ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:834:93: error: no member named 'asinf' in the global namespace; did you mean 'asin'?
inline _LIBCPP_INLINE_VISIBILITY float       asin(float __lcpp_x) _NOEXCEPT       {return ::asinf(__lcpp_x);}
                                                                                          ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:834:46: note: 'asin' declared here
inline _LIBCPP_INLINE_VISIBILITY float       asin(float __lcpp_x) _NOEXCEPT       {return ::asinf(__lcpp_x);}
                                             ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:835:93: error: no member named 'asinl' in the global namespace; did you mean 'asin'?
inline _LIBCPP_INLINE_VISIBILITY long double asin(long double __lcpp_x) _NOEXCEPT {return ::asinl(__lcpp_x);}
                                                                                          ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:834:46: note: 'asin' declared here
inline _LIBCPP_INLINE_VISIBILITY float       asin(float __lcpp_x) _NOEXCEPT       {return ::asinf(__lcpp_x);}
                                             ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:841:38: error: call to 'asin' is ambiguous
asin(_A1 __lcpp_x) _NOEXCEPT {return ::asin((double)__lcpp_x);}
                                     ^~~~~~
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:834:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY float       asin(float __lcpp_x) _NOEXCEPT       {return ::asinf(__lcpp_x);}
                                             ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:835:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long double asin(long double __lcpp_x) _NOEXCEPT {return ::asinl(__lcpp_x);}
                                             ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:846:93: error: no member named 'atanf' in the global namespace; did you mean 'atan'?
inline _LIBCPP_INLINE_VISIBILITY float       atan(float __lcpp_x) _NOEXCEPT       {return ::atanf(__lcpp_x);}
                                                                                          ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:846:46: note: 'atan' declared here
inline _LIBCPP_INLINE_VISIBILITY float       atan(float __lcpp_x) _NOEXCEPT       {return ::atanf(__lcpp_x);}
                                             ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:847:93: error: no member named 'atanl' in the global namespace; did you mean 'atan'?
inline _LIBCPP_INLINE_VISIBILITY long double atan(long double __lcpp_x) _NOEXCEPT {return ::atanl(__lcpp_x);}
                                                                                          ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:846:46: note: 'atan' declared here
inline _LIBCPP_INLINE_VISIBILITY float       atan(float __lcpp_x) _NOEXCEPT       {return ::atanf(__lcpp_x);}
                                             ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:853:38: error: call to 'atan' is ambiguous
atan(_A1 __lcpp_x) _NOEXCEPT {return ::atan((double)__lcpp_x);}
                                     ^~~~~~
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:846:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY float       atan(float __lcpp_x) _NOEXCEPT       {return ::atanf(__lcpp_x);}
                                             ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:847:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long double atan(long double __lcpp_x) _NOEXCEPT {return ::atanl(__lcpp_x);}
                                             ^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:858:116: error: no member named 'atan2f' in the global namespace; did you mean 'atan2'?
inline _LIBCPP_INLINE_VISIBILITY float       atan2(float __lcpp_y, float __lcpp_x) _NOEXCEPT             {return ::atan2f(__lcpp_y, __lcpp_x);}
                                                                                                                 ~~^
../../buildtools/mac-x64/clang/bin/../include/c++/v1/math.h:858:46: note: 'atan2' declared here
inline _LIBCPP_INLINE_VISIBILITY float       atan2(float __lcpp_y, float __lcpp_x) _NOEXCEPT             {return ::atan2f(__lcpp_y, __lcpp_x);}
                                             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

My google-fu was too weak for this issue :(

**Comment by athomas** [comment]
Likely the cause here is a too new version of xcode (the build uses an `11.3` macOS SDK which implies xcode `12.5` which is the very latest). Supporting the latest versions of xcode won't work until at least  https://dart-review.googlesource.com/c/sdk/+/193823 has landed (which is currently blocked on the `10.14` upgrade of the Mac infrastructure because the clang toolchain is incompatible with the older versions of xcode needed to build on `10.13`).

I tested Xcode 12.2 (12B45b) and Xcode 11.3.1 (11C505).

**Comment by Calin-Cosma** [comment]
Unless I am mistaken, that one seems to talk about M1 CPUs
I am on an Intel CPU: 4,2 GHz Quad-Core Intel Core i7 (from 2017)

If that also covers Intel CPUs, I hope they manage to push the fix ASAP

**Comment by Calin-Cosma** [comment]
Thanks for your replies. It's not something very urgent, so I'll make do
for the time being.

I would have liked to be sure that was the issue and not something else.
Perhaps I'm gonna look into multiple versions of XCode, even if I am a bit
wary of breaking some stuff that's needed by Flutter or some other
tools/sdks that I am currently using.

**Comment by DanTup** [comment]
I hit this same issue today, and switching to the older Xcode did fix it for me. Here's the steps I took:

- downloaded Xcode 12.2 from https://download.developer.apple.com/Developer_Tools/Xcode_12.2/Xcode_12.2.xip
- extracted the file (double-click on it in Finder)
- renamed it to Xcode_12.2.app
- moved it to /Applications
- ran `sudo xcode-select -s /Applications/Xcode_12.2.app/Contents/Developer`

Switching back to the Store-installed Xcode can be done with `sudo xcode-select -r` (and you can use `xcode-select -p` to check which one is set).

**Comment by athomas** [comment]
I'm closing this issue given that a workaround has been provided that will address the problem.
