### ISSUE TITLE
Analyzer Feedback from IntelliJ

### ISSUE THREAD

**Issue by rock3r** [dart-lang/sdk#31330]
Got this while working on the Flutter SDK in IDEA 2017.3 EAP.

# Version information

- `IDEA 173.3531.6`
- `1.25.0-dev.11.0`
- `IC-173.3531.6, JRE 1.8.0_152-release-1024-b6x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.13.1 unknown, screens 1680x1050  Retina`

# Exception

```
Dart analysis server, SDK version 1.25.0-dev.11.0, server version 1.18.4, error: Exception while using a _Visitor to visit a InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in InstanceCreationExpressionImpl in VariableDeclarationImpl in VariableDeclarationListImpl in VariableDeclarationStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in ArgumentListImpl in MethodInvocationImpl in ExpressionStatementImpl in BlockImpl in BlockFunctionBodyImpl in FunctionExpressionImpl in FunctionDeclarationImpl in CompilationUnitImpl
NoSuchMethodError: The method 'accept' was called on null.
Receiver: null
Tried calling: accept(Instance of 'ConstantVisitor')
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      ConstantVisitor._valueOf (package:analyzer/src/dart/constant/evaluation.dart:1676)
#3      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:453)
#4      ConstantEvaluationEngine.evaluateConstructorCall (package:analyzer/src/dart/constant/evaluation.dart:749)
#5      ConstantVerifier.visitInstanceCreationExpression (package:analyzer/src/generated/resolver.dart:1466)
#6      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6447)
#7      _Visitor.visitInstanceCreationExpression (package:linter/src/rules/prefer_const_constructors.dart:93)
#8      InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6447)
#9      ExceptionHandlingDelegatingAstVisitor.visitNode.<anonymous closure> (package:analyzer/src/dart/ast/utilities.dart:2756)
#10     List.forEach (dart:core-patch/growable_array.dart:267)
#11     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2754)
#12     UnifyingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:3069)
#13     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6447)
#14     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7709)
#15     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#16     UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3112)
#17     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7704)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#19     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:428)
#20     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#21     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:2898)
#22     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:424)
#23     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6452)
#24     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#25     UnifyingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:3069)
#26     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6447)
#27     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7709)
#28     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#29     UnifyingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:3112)
#30     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7704)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#32     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:428)
#33     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#34     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:2898)
#35     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:424)
#36     InstanceCreationExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6452)
#37     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#38     UnifyingAstVisitor.visitInstanceCreationExpression (package:analyzer/dart/ast/visitor.dart:3069)
#39     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6447)
#40     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11054)
#41     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#42     UnifyingAstVisitor.visitVariableDeclaration (package:analyzer/dart/ast/visitor.dart:3224)
#43     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:11048)
#44     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#45     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11150)
#46     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#47     UnifyingAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:3228)
#48     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:11144)
#49     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11205)
#50     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#51     UnifyingAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:3232)
#52     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11201)
#53     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#54     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1346)
#55     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#56     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#57     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1342)
#58     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1291)
#59     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#60     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#61     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1287)
#62     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5319)
#63     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#64     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#65     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5313)
#66     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#67     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:428)
#68     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#69     UnifyingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:2898)
#70     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:424)
#71     MethodInvocationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7605)
#72     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#73     UnifyingAstVisitor.visitMethodInvocation (package:analyzer/dart/ast/visitor.dart:3109)
#74     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7598)
#75     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4228)
#76     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#77     UnifyingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:3005)
#78     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4224)
#79     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#80     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1346)
#81     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#82     UnifyingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:2919)
#83     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1342)
#84     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1291)
#85     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#86     UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:2922)
#87     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1287)
#88     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5319)
#89     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#90     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3033)
#91     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5313)
#92     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5164)
#93     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#94     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3026)
#95     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5157)
#96     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7990)
#97     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2502)
#98     ExceptionHandlingDelegatingAstVisitor.visitNode (package:analyzer/src/dart/ast/utilities.dart:2761)
#99     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:2949)
#100    CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2495)
#101    LibraryAnalyzer._computeLints (package:analyzer/src/dart/analysis/library_analyzer.dart:250)
#102    LibraryAnalyzer._analyze.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:132)
#103    _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#104    LibraryAnalyzer._analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:131)
#105    _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#106    LibraryAnalyzer._analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:130)
#107    LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:64)
#108    _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#109    LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:63)
#110    AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1075)
#111    PerformanceLog.run (package:front_end/src/base/performace_logger.dart:34)
#112    AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1063)
#113    AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:920)
<asynchronous suspension>
#114    AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1615)
<asynchronous suspension>
#115    AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1558)
#116    new AnalysisServer (package:analysis_server/src/analysis_server.dart:383)
#117    SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86)
#118    StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#119    Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:434)
#120    _rootRun (dart:async/zone.dart:1120)
#121    _CustomZone.run (dart:async/zone.dart:1001)
#122    runZoned (dart:async/zone.dart:1467)
#123    Driver._captureExceptions (package:analysis_server/src/server/driver.dart:473)
#124    Driver.start (package:analysis_server/src/server/driver.dart:433)
#125    main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analysis_server/bin/server.dart:12)
#126    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#127    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

```

```
1510220989731 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/list_view_fling_test.dart","errors":[]}}
1510220989764 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/icon_test.dart","errors":[]}}
1510220989780 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/grid_paper_test.dart","errors":[]}}
1510220989801 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/list_view_correction_test.dart","errors":[]}}
1510220989819 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/media_query_test.dart","errors":[]}}
1510220989844 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/scrollable_list_hit_testing_test.dart","errors":[]}}
1510220989863 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/title_test.dart","errors":[]}}
1510220989878 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/center_test.dart","errors":[]}}
1510220989917 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/animated_positioned_test.dart","errors":[]}}
1510220989937 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/slivers_appbar_floating_pinned_test.dart","errors":[]}}
1510220989959 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/syncing_test.dart","errors":[]}}
1510220989978 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/scroll_notification_test.dart","errors":[]}}
1510220990002 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/custom_multi_child_layout_test.dart","errors":[]}}
1510220990034 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/box_decoration_test.dart","errors":[]}}
1510220990063 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/scroll_events_test.dart","errors":[]}}
1510220990081 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/overlay_test.dart","errors":[]}}
1510220990103 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/safe_area_test.dart","errors":[]}}
1510220990143 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/scrollable_semantics_test.dart","errors":[]}}
1510220990178 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/drawer_test.dart","errors":[]}}
1510220990210 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/scroll_view_test.dart","errors":[]}}
1510220990230 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/rtl_test.dart","errors":[]}}
1510220990250 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/raw_keyboard_listener_test.dart","errors":[]}}
1510220990278 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/keep_alive_test.dart","errors":[]}}
1510220990304 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/scrollable_fling_test.dart","errors":[]}}
1510220990330 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/semantics_3_test.dart","errors":[]}}
1510220990349 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/binding_test.dart","errors":[]}}
1510220990365 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/default_text_style_test.dart","errors":[]}}
1510220990413 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/stack_test.dart","errors":[]}}
1510220990433 <= {"event":"analysis.errors","params":{"file":"/Users/rock3r/src/flutter/packages/flutter/test/widgets/key_test.dart","errors":[]}}
1510220990467 <= {"event":"server.error","params":{"isFatal":false,"message":"Exception while using a _Visitor to visit a InstanceCreationExpressionImpl in NamedExpressionImpl in ArgumentListImpl in I
```

**Comment by bwilkerson** [comment]
I'm assuming that this is stale. Please let us know if you're still seeing this problem.
