### ISSUE TITLE
Analyzer and get with generics returns incorrectly error

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/sdk#31093]
I don't think 'get' is a reserved word and using get as a method is a bad practice.  However get used in this context see line #7. 

```
001 // Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
002 // for details. All rights reserved. Use of this source code is governed by a
003 // BSD-style license that can be found in the LICENSE file.
004 //
005 // VMOptions=--generic-method-syntax
006 
007 List<T> get<T>(T item) => <T>[item];
008 List<T> get2<T>(T item) => <T>[item];
009 
010 void main() {
011 print(get(1));
012  print(get2(1));
013 }
```

Compilation Errors:

```
[error] The name 'T' isn't a type so it can't be used as a type argument. (tests/language_2/regress_29349_test.dart, line 7, col 6)
[error] Expected an identifier. (tests/language_2/regress_29349_test.dart, line 7, col 12)
[error] Getters must be declared without a parameter list. (tests/language_2/regress_29349_test.dart, line 7, col 15)
[error] The name 'T' isn't a type so it can't be used as a type argument. (tests/language_2/regress_29349_test.dart, line 7, col 28)
[error] Undefined name 'item'. (tests/language_2/regress_29349_test.dart, line 7, col 31)
[error] The function 'get' isn't defined. (tests/language_2/regress_29349_test.dart, line 11, col 8)

```

**Comment by srawlins** [comment]
Duplocate of #29744
