### ISSUE TITLE
Erroneous error about an unexhaustive switch in dart2js only

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#51823]
Related to https://github.com/flutter/flutter/pull/123242.

Building a dart2js app internally without that change results in the following error:

```
package:flutter/src/widgets/focus_traversal.dart:474:28:
Error: The type 'TraversalEdgeBehavior' is not exhaustively matched by the switch cases.
 - 'TraversalEdgeBehavior' is from 'package:flutter/src/widgets/focus_traversal.dart'.
      switch (nearestScope.traversalEdgeBehavior) {
                           ^
package:flutter/src/widgets/focus_traversal.dart:492:28:
Error: The type 'TraversalEdgeBehavior' is not exhaustively matched by the switch cases.
 - 'TraversalEdgeBehavior' is from 'package:flutter/src/widgets/focus_traversal.dart'.
      switch (nearestScope.traversalEdgeBehavior) {
                           ^
Error: Compilation failed.
```

This can be "fixed" by changing [this line](https://github.com/dart-lang/sdk/blob/cbe7075b7aefeb7958222d09335f23a7c2997404/pkg/compiler/lib/src/kernel/dart2js_target.dart#L241) to pass an explicit `false` and changing [this line](https://github.com/dart-lang/sdk/blob/cbe7075b7aefeb7958222d09335f23a7c2997404/pkg/compiler/lib/src/phase/load_kernel.dart#L223) to set an explicit `true` as well. Essentially, forcing the CFE to evaluate constants eagerly.

 cc @sigmundch for triage, I am not sure if I should assign this to area-web or area-frontend

**Comment by sigmundch** [comment]
I believe this is a CFE issue, but I need to iterate longer on a smaller repro. Unfortunately, the dependency from this to the flutter SDK makes it a bit harder to do a local repro than I anticipated (our trick with the .input.tar only gets us part way there).

@johnniwinther - the main difference between the two runs is whether we evaluate all constants eagerly or not, and that seems to be triggering the problem. Even though there aren't any fromEnvironment variables in this specific part of the program.

**Comment by johnniwinther** [comment]
Is the Flutter build modular or monolithic?

**Comment by jakemac53** [comment]
I am about 90% sure it was monolithic but tbh its a bit difficult to promise that :)

**Comment by sigmundch** [comment]
Definitely monolithic. That said, the SDK is always built separately.

@johnniwinther - I wasn't able to create a smaller repro unfortuantely, but I'll share with you steps for how to repro this on your local machine
