### ISSUE TITLE
WebGl issue occuring both on Dartium and using dart2js

### ISSUE THREAD

**Issue by boasjls** [dart-lang/sdk#25979]
**Summary:**
Web-applications which require WebGL do not work with the dart-sdk-1.16-dev.0.0
This issue appears both when the application is executed on Dartium, 
and when it is run on a dart2js based platform, e.g. firefox.

**What steps will reproduce the problem?**
1) Open webstorm and clone the sample-pop_pop_win application
https://github.com/dart-lang/sample-pop_pop_win
2) Run the application
*Expected:*
The application runs as usual

*Actual:*
The application fails during initialization.

*On dartium the browser console output yields:*
Uncaught Unhandled exception:
The null object does not have a method 'setTransform'.

NoSuchMethodError: method not found: 'setTransform'
Receiver: null
Arguments: [1.0, 0.0, 0.0, 1.0, 0.0, 0.0]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      RenderContextCanvas.setTransform (package:stagexl/src/engine/render_context_canvas.dart:308:23)
#3      RenderContextCanvas.reset (package:stagexl/src/engine/render_context_canvas.dart:27:5)
#4      RenderContextCanvas.RenderContextCanvas (package:stagexl/src/engine/render_context_canvas.dart:16:10)
#5      Stage._createRenderContext (package:stagexl/src/display/stage.dart:361:20)
#6      Stage.Stage (package:stagexl/src/display/stage.dart:150:22)
#7      startGame.<startGame_async_body> (package:pop_pop_win/pop_pop_win.dart:25:19)
#8      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#11     _ScheduleImmediateHelper._handleMutation (dart:html:52090)
#12     MutationObserver._create.<anonymous closure> (dart:html:28787)

*On firefox the browser console output yields:*
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create game_web.dart.js:164:7
unreachable code after return statement game_web.dart.js:1:57
unreachable code after return statement game_web.dart.js:1:61
Error: 
 game_web.dart.js:2467:17

**What version of the product are you using?**
Dartium and dart-sdk: 1.16-dev.0.0
Webstorm: 11.0.3

**Comment by mit-mit** [comment]
CC @terrylucas @jacob314 @kevmoo

**Comment by alan-knight** [comment]
I think this is a duplicate of #26047
