### ISSUE TITLE
[js_interop]: "Uncaught TypeError: J.d5(...).Y is not a function" when importing "dart:js_util" library together

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/sdk#44150]
Dart version: 2.9.3~2.10.2

When using `@JS()` js_interop with a Dart class like **Win** in `js_interop.dart` and importing the library `dart:js_util` in `main.dart` together, all the methods defined inside **Win** will be lost in Dart2JS compiler.

For example,

### main.dart
```dart
import 'dart:js_util';
import 'js_interop.dart';

main () {
   
    /// The following code only works separately
    window.eval('console.log("test")');
    callMethod(window, 'eval', ['console.log("test2")']);
}
```
As you can see, if we comment out either line in the **main** function, it works well with Dart2JS compiler.

### js_interop.dart

```dart
@JS()
library dart.issue.js;

import 'package:js/js.dart';

@JS()
@anonymous
abstract class Win {
  external eval(String script);
}

@JS()
external Win get window
```

Here is a whole test project to demonstrate this issue - https://github.com/jumperchen/dart_interop_bug

**Comment by sigmundch** [comment]
Thanks for filing the bug!

Currently there is a limitation that makes native types exposed via `dart:html` not available to be exposed via JS-interop. 

In your case, you are not importing `dart:html` directly, so it is surprising to see this problem, however there is an indirect dependency from `package:js` to `dart:js` to `dart:html`. The `js_util` methods make dart2js keep alive that dependency that would otherwise be tree-shaken. We are tracking this dependency problem in https://github.com/dart-lang/sdk/issues/42736.

Removing that dependency will fix your example (in fact we have a second implementation of `dart:js` to support node.js when running `dart2js --server-mode` and I can verify that your application works there with both lines uncommented). However, I wonder whether that would be enough in your case. Do you intend to only access the browser APIs via js-interop, or do expect to combine your code with other libraries that use `dart:html`? If other code in the same app can access `dart:html`, you'll hit the limitation again through a different dependency.

In terms of the limitation of combining native and js-interop types: we plan to add checks to detect when this happens to help inform you at compile-time (see https://github.com/dart-lang/sdk/issues/32929#issuecomment-660389743). 

@srujzs is also adding documentation describing this problem and what workarounds are available for some scenarios ([cl][1], [doc][2]). There are also additional details on https://github.com/dart-lang/sdk/issues/39753.

I'm marking this issue closed since our next steps are captured by https://github.com/dart-lang/sdk/issues/42736 and https://github.com/dart-lang/sdk/issues/32929#issuecomment-660389743.

[1]: https://dart-review.googlesource.com/c/sdk/+/171629
[2]: https://github.com/dart-lang/sdk/blob/master/sdk/lib/html/doc/WORKAROUNDS.md

**Comment by jumperchen** [comment]
@sigmundch Thanks for the explanation, we did use `dart:html` in our application as well, so we could hit this limitation again, however, we found a workaround to avoid this issue for now.
